name: eggnstone_dart
description: A collection of Dart tools, including wrappers for logging.
homepage: https://github.com/eggnstone/eggnstone_dart

version: 1.1.0

environment:
  sdk: ^3.0.0

dependencies:
  intl: ^0.19.0

dev_dependencies:
  test: ^1.25.2
