name: eggnstone_dart
description: A collection of Dart tools, including wrappers for logging.
homepage: https://github.com/eggnstone/eggnstone_dart

version: 1.1.1

environment:
  sdk: ^3.0.0

dependencies:
  intl: ^0.20.1

dev_dependencies:
  test: any
