name: eggnstone_dart
description: A collection of Dart tools, including wrappers for logging.
homepage: https://github.com/eggnstone/eggnstone_dart
version: 1.4.0

environment:
  sdk: ^3.0.0

dependencies:
  freezed_annotation: ^3.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  sprintf: ^7.0.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  test: any
