name: eggnstone_dart
description: A collection of Dart tools, including wrappers for logging.
homepage: https://pub.dev/publishers/eggnstone.dev/packages

version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # Internationalization (for logger)
  intl: ^0.18.0

dev_dependencies:
  test: ^1.23.1
