name: eggnstone_dart
description: A collection of Dart tools, including wrappers for logging.
homepage: https://github.com/eggnstone/eggnstone_dart

version: 1.2.3

environment:
  sdk: ^3.0.0

dependencies:
  freezed_annotation: ^2.4.4
  intl: ^0.20.1
  json_annotation: ^4.9.0
  sprintf: ^7.0.0

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.8
  frontend_server_client: ^4.0.0 # Necessary because of: Precompiling build script...... Could not find a command named frontend_server.dart.snapshot
  json_serializable: ^6.9.3
  test: any
